// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/collections/:collectionHandle": {
    params: {
      "collectionHandle": string;
    };
  };
  "/policies/privacy-policy": {
    params: {};
  };
  "/products/:productHandle": {
    params: {
      "productHandle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/google-feed.xml": {
    params: {};
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/sanity-preview": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/searchresults": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/blogComments": {
    params: {};
  };
  "/newsletter": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/homepage": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/address/:id": {
    params: {
      "id": string;
    };
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/edit": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/sitemap": {
    params: {};
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/splash": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog/:blogHandle/:articleHandle" | "/collections/:collectionHandle" | "/policies/privacy-policy" | "/products/:productHandle" | "/account/authorize" | "/collections" | "/google-feed.xml" | "/blogs/:blogHandle" | "/account/logout" | "/collections/all" | "/products" | "/account/login" | "/sanity-preview" | "/sitemap.xml" | "/pages/:handle" | "/searchresults" | "/robots.txt" | "/blogComments" | "/newsletter" | "/locations" | "/homepage" | "/account" | "/account/address/:id" | "/account/orders/:id" | "/account/edit" | "/account/*" | "/sitemap" | "/sitemap/:type/:page.xml" | "/splash" | "/cart" | "/*";
  };
  "routes/blog.$blogHandle.$articleHandle.tsx": {
    id: "routes/blog.$blogHandle.$articleHandle";
    page: "/blog/:blogHandle/:articleHandle";
  };
  "routes/collections.$collectionHandle.tsx": {
    id: "routes/collections.$collectionHandle";
    page: "/collections/:collectionHandle";
  };
  "routes/policies.privacy-policy.tsx": {
    id: "routes/policies.privacy-policy";
    page: "/policies/privacy-policy";
  };
  "routes/products.$productHandle.tsx": {
    id: "routes/products.$productHandle";
    page: "/products/:productHandle";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/[google-feed.xml].tsx": {
    id: "routes/[google-feed.xml]";
    page: "/google-feed.xml";
  };
  "routes/blogs.$blogHandle.tsx": {
    id: "routes/blogs.$blogHandle";
    page: "/blogs/:blogHandle";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/collections.all.tsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/products._index.tsx": {
    id: "routes/products._index";
    page: "/products";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/sanity-preview.tsx": {
    id: "routes/sanity-preview";
    page: "/sanity-preview";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/searchresults.tsx": {
    id: "routes/searchresults";
    page: "/searchresults";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/blogComments.tsx": {
    id: "routes/blogComments";
    page: "/blogComments";
  };
  "routes/newsletter.tsx": {
    id: "routes/newsletter";
    page: "/newsletter";
  };
  "routes/locations.tsx": {
    id: "routes/locations";
    page: "/locations";
  };
  "routes/homepage.tsx": {
    id: "routes/homepage";
    page: "/homepage";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/address/:id" | "/account/orders/:id" | "/account/edit" | "/account/*";
  };
  "routes/account.address.$id.tsx": {
    id: "routes/account.address.$id";
    page: "/account/address/:id";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.edit.tsx": {
    id: "routes/account.edit";
    page: "/account/edit";
  };
  "routes/account.$.tsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/sitemap.tsx": {
    id: "routes/sitemap";
    page: "/sitemap" | "/sitemap/:type/:page.xml";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/splash.tsx": {
    id: "routes/splash";
    page: "/splash";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};